image: alvrme/alpine-android:android-29

variables:
  SIGNING_KEY: /builds/breadwallet/breadwallet-android/FakeSigningKey
  SIGNING_PASSWORD: qwerty
  SIGNING_ALIAS: key0
  SIGNING_ALIAS_PASSWORD: qwerty
  ORG_GRADLE_DAEMON: "false"
  ORG_GRADLE_DEPENDENCY_VERIFICATION: "off"
  ORG_GRADLE_CONSOLE: plain

cache:
  key: ${CI_PROJECT_ID}-3
  paths:
    - ~/.gradle/
    - /root/.gradle/

#detekt:
#  stage: test
#  script:
#    - ./gradlew detekt
#  only:
#    - merge_requests
#  artifacts:
#    expose_as: "Detekt Report"
#    paths:
#      - app/build/reports/detekt/detekt.html

build:
  stage: build
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew build -xlint -xdetekt
  only:
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    paths:
      - app/build/outputs/apk/xwllaet/debug/
      - app/build/outputs/apk/xwllaet/release/
      - app/build/outputs/apk/xwllaetTestnet/debug/
      - app/build/outputs/apk/xwllaetTestnet/release/
    reports:
      junit: ./**/build/test-results/**/TEST-*.xml

deploy-appetize:
  stage: deploy
  needs: [ "build" ]
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew appetizeUpload
  only:
    - merge_requests
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    url: $NATIVE_REVIEW_URL?versionName=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    on_stop: stop-review

stop-review:
  stage: deploy
  needs: [ "build" ]
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - cd $CI_PROJECT_DIR; ./gradlew appetizeRemove -Pmerge=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  when: manual
  only:
    - merge_requests
  environment:
    name: Review $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    action: stop

deploy-firebase:
  stage: deploy
  variables:
    ORG_GRADLE_DEPENDENCY_VERIFICATION: "off"
  script:
    - git submodule sync
    - git submodule update --init --force --remote
    - ./gradlew assemble appDistributionUploadBrdRelease appDistributionUploadBrdTestnetRelease appDistributionUploadBrdDebug appDistributionUploadBrdTestnetDebug
  rules:
    - if: '$CI_COMMIT_TAG != null'
  artifacts:
    paths:
      - app/build/outputs/apk/xwallet/debug/
      - app/build/outputs/apk/xwallet/release/
      - app/build/outputs/apk/xwalletTestnet/debug/
      - app/build/outputs/apk/xwalletTestnet/release/
